### ISSUE TITLE
Swap bug

### ISSUE THREAD

**Issue by ghost** [dFed-finance/interface#17]
No matter what I do swap doesn't want get through. When I input number and going to click swap, my number change to zero instantly:
![image](https://user-images.githubusercontent.com/75580360/101287415-72a49700-37f0-11eb-9551-6052476bc304.png)

Result:
![image](https://user-images.githubusercontent.com/75580360/101287425-83eda380-37f0-11eb-989d-e296eff49d45.png)

**Comment by ghost** [comment]
Please refresh that page and try again ~

**Comment by ghost** [comment]
I figured it out. When you input second currency  "TO", swap doesn't get executed. You put any number and it reset to 0. But if you input first currency "FROM" and click swap it does work properly. But it should work both ways.

**Comment by shawnying** [comment]
We have reproduced your problem as you described. It's a bug! Thank you very much!

**Comment by shawnying** [comment]
Could you please provide more details such as screen captures

**Comment by shawnying** [comment]
Please leave me your ETH address & email to get rewards

**Comment by diemou** [comment]
> Please leave me your ETH address & email to get rewards

Email: ivan.mlnk2@gmail.com
ETH address: 0x3fE6D3F40ff6CC8C42643ab4ae3E198342B92056
Discord: diemou#0386
