### ISSUE TITLE
Can't create pool for alpha FED (0xaa5c55e80a1fe90015d06e1ac28b3a7676f3d985)

### ISSUE THREAD

**Issue by script-money** [dFed-finance/interface#19]
<img width="670" alt="Screen Shot 2020-12-07 at 3 03 55 PM" src="https://user-images.githubusercontent.com/74860630/101319788-7c380880-389d-11eb-97fb-ebc8326207d1.png">

**Comment by ghost** [comment]
Because aFED is not a normal ERC20, its transfer function has been disabled. It is only a proof.
So it is not a bug. You can try other tokens.

**Comment by script-money** [comment]
> Because aFED is not a normal ERC20, its transfer function has been disabled. It is only a proof.
> So it is not a bug. You can try other tokens.

Does Fed on main-net has transfer function?
